<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessRepository extends EntityRepository
{
    public function findTodayAccesses()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Access a ORDER BY a.endDate DESC'
            )
            ->getResult();
    }
}
